[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-library"
version = "0.1.0"
description = "Simple demo library"
authors = [
  { name = "Rushikesh" }
]
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["hello_library*"]